services:
  db:
    image: mysql:8.0
    container_name: dws_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_system
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./Backend
    container_name: dws_go_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ticket_system
      - JWT_SECRET=clave_secreta_para_los_tokens_de_juan_123
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./Frontend
    container_name: dws_react_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
